# coding=utf-8
import logging

from django import db
from django.db import connection


__author__ = 'edwardotis'

logger = logging.getLogger(__name__)


def log_and_clear_queries():
    '''
    In order to see the sql generated by an ORM db call, you can use this
    utility method.
    It deletes the query log after it runs.
    :return:
    '''
    if connection.queries:
        for query in connection.queries:
            logger.debug(query)
        db.reset_queries()